language: node_js
node_js:
  - "7"
services:
  - postgresql
before_script:
  - psql -c 'create database ash_test;' -U postgres
after_success:
  - npm run docs
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
